### PR TITLE
Serve docs at /docs. Close #130

### LINKED ISSUE #130: Serve docs at /docs
Docs should be served by the services server. This funcionality was lost in the migration to a separate codebase; it used to be hosted by the main server but generated by the services server.

### PR DESCRIPTION
**Pull request by brollb**
This updates the server to host the docs at /docs.

However, it appears that there is still an issue with the build step. @dragazo, would you mind taking a look at this?

### CODE REVIEW

**Comment by dragazo** [comment]
Sure, I can look into it - so when you say the build step has an issue, what is the build process? It should just need a `node utils/build-docs.js`, but it looks like that's not successfully starting the services (as being hosted on `localhost:8080`). I'm not sure what the new process is for starting that from the docs build script, so we might just need to change the build process to start hosting in the background, wait a few seconds, then build the docs in a separate process.

**Comment by brollb** [comment]
Sorry for being vague. I don't actually mind starting the server first then running the build docs command (I actually prefer it) but I am running into the following errors:
```
Error: failed to compile docs:
error:

important:
/home/brian/projektek/netsblox/services/docs/_generated/fundamentals/rpc-arg-types.rst:11: WARNING: unknown document: '/services/PhoneIoT/index'
/home/brian/projektek/netsblox/services/docs/_generated/fundamentals/rpc-arg-types.rst:153: WARNING: unknown document: '/services/PhoneIoT/index'
/home/brian/projektek/netsblox/services/docs/_generated/fundamentals/rpc-arg-types.rst:181: WARNING: unknown document: '/services/PhoneIoT/index'
/home/brian/projektek/netsblox/services/docs/_generated/fundamentals/rpc-arg-types.rst:233: WARNING: unknown document: '/services/FinancialData/index'
/home/brian/projektek/netsblox/services/docs/_generated/fundamentals/rpc-arg-types.rst:261: WARNING: unknown document: '/services/PhoneIoT/index'
/home/brian/projektek/netsblox/services/docs/_generated/fundamentals/rpc-arg-types.rst:311: WARNING: unknown document: '/services/FinancialData/index'
/home/brian/projektek/netsblox/services/docs/_generated/fundamentals/rpc-arg-types.rst:325: WARNING: unknown document: '/services/PhoneIoT/index'
/home/brian/projektek/netsblox/services/docs/_generated/fundamentals/rpc-arg-types.rst:339: WARNING: unknown document: '/services/PhoneIoT/index'
/home/brian/projektek/netsblox/services/docs/_generated/fundamentals/rpc-arg-types.rst:587: WARNING: unknown document: '/services/PhoneIoT/index'
/home/brian/projektek/netsblox/services/docs/_generated/fundamentals/rpc-arg-types.rst:599: WARNING: unknown document: '/services/PhoneIoT/index'
/home/brian/projektek/netsblox/services/docs/_generated/fundamentals/rpc-arg-types.rst:649: WARNING: unknown document: '/services/PhoneIoT/index'
/home/brian/projektek/netsblox/services/docs/_generated/fundamentals/rpc-arg-types.rst:675: WARNING: unknown document: '/services/PhoneIoT/index'
/home/brian/projektek/netsblox/services/docs/_generated/fundamentals/rpc-arg-types.rst:802: WARNING: unknown document: '/services/FinancialData/index'
/home/brian/projektek/netsblox/services/docs/_generated/fundamentals/rpc-arg-types.rst:816: WARNING: unknown document: '/services/PhoneIoT/index'
/home/brian/projektek/netsblox/services/docs/_generated/fundamentals/rpc-arg-types.rst:830: WARNING: unknown document: '/services/PhoneIoT/index'

ignored:
/home/brian/projektek/netsblox/services/docs/_generated/services/NewYorkTimes/Concepts.rst:15: WARNING: duplicate function description of NewYorkTimes.getArticlesWithConcept, other function in services/NewYorkTimes/Articles

stdout:
Removing everything under '_build'...
```
The docs page looked incorrect but I just realized that I was serving `docs/_build/html` rather than `docs/_generated/_build/html` :)

**Comment by brollb** [comment]
I am going to go ahead and merge this but it would be nice to add building the docs to the CI to make sure there we stay on top of any errors like that one (even if it doesn't appear to be causing any real issues).

**Comment by dragazo** [comment]
Ah gotcha. Well for those errors, those look like they're coming from the arg types list, which is generated from types metadata. I think the issue might be that the types get defined even if the service is not available. In that case, they still get a types metadata entry, but the service isn't available so the service-specific pages aren't copied over (hence the unknown file error). I think that might actually be a flaw in the way we define types. Ideally, we could make the type tape be wiped if the service turns out to not be supported (e.g., from missing env vars) after loading.

**Pull request merged**
