### PR TITLE
Restrict RPC Idents

### PR DESCRIPTION
**Pull request by dragazo**
[Problem Origin](https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/pull/1347). Adds a utility called `assertValidIdent` that can be used to check identifiers for all service-creation features. Currently, this is only enforced in `ServiceCreation.createServiceFromTable`.

The current checker is very restrictive (mostly C ident plus common separators like `-_ `), but should allow 99% of all reasonable symbol names. All existing RPCs would pass this check except for some of the `Geolocation` services that have an asterisk in their name. But that's fine since this is technically only used for user-created services (and specifically only new services).

_Note: the change to `ServiceCreation` is currently untested because logging in doesn't seem to be working (created a test user, but logging in gives a "must be logged in" error since the `netsblox` cookie gets rejected due to invalid domain)_

### CODE REVIEW

**Comment by dragazo** [comment]
@gsteinLTU I just added service/rpc/arg name checks for IoTScape services, but I'm not sure how to test it.

**Comment by gsteinLTU** [comment]
Looks good, and I can test it. Might be a little while but I'll be able to.

**Comment by gsteinLTU** [comment]
It needed to be added to a second location in IoTScape.

**Review by brollb — COMMENTED** [review]
Looks good! I would also add this check to the services defined in JS on server start (crash with an error if any server fails validation). Here is an example of an existing validation run on server startup: https://github.com/NetsBlox/services/blob/main/src/services-worker.js#L123-L125

**Comment by brollb** [comment]
Good point. It would be nice to have some checks for the JS services, too... What if we kept it restrictive and just allowed trailing asterisks? These could also be trivially converted to C identifiers by just stripping them off.

**Comment by dragazo** [comment]
Ok, I just pushed a version that checks js service/rpc/arg names and is still maximum restrictive. The checker is unchanged, but fs rpc names (and only rpc names) are first stripped of trailing asterisks before checking validity. So now all identifiers everywhere satisfy this checker, with the sole exception of fs rpc names allowing trailing asterisks.

**Comment by brollb** [comment]
@dragazo - Could you add some tests? Then it should be good to merge!

**Comment by dragazo** [comment]
@brollb Ok, I just added some tests. I also fixed an import typo in the wildcam service that was making the test framework crash.

**Comment by brollb** [comment]
LGTM. Thanks @dragazo and @gsteinLTU!

**Pull request merged**
