### PR TITLE
Profanity-checked string input type for RPCs

### LINKED ISSUE #20: Profanity detection for services (at least ServiceCreation)
It might be possible to just build this into the type system for RPCs (as long as the profanity checking isn't too overzealous).

### PR DESCRIPTION
**Pull request by gsteinLTU**
Closes #20

### CODE REVIEW

**Comment by brollb** [comment]
I would set the display name to `String` for the documentation so it is indistinguishable from the regular string type for end users - then it should be good to merge!

**Comment by gsteinLTU** [comment]
Added a displayName, let me know if that works how you wanted.

**Comment by dragazo** [comment]
Since it now had the same display name as `String` it should have been crashing at define time, but wasn't. I just fixed the name checker bug, and fixed the underlying name conflict by marking the new string type as hidden. It should be good to go now.

**Comment by brollb** [comment]
LGTM. Thanks, @gsteinLTU and @dragazo!

**Pull request merged**
